services:
  identifica-postgres:
    image: postgres:16
    container_name: identifica-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: informamz
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  identifica-pgadmin:
    image: dpage/pgadmin4
    container_name: identifica-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@informamz.gov.mz
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"

volumes:
  postgres_data:
